# Generated by Django 4.2.5 on 2023-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmngugiwebsite', '0003_alter_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKEditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ckeditor_images/')),
            ],
        ),
    ]
