# Generated by Django 4.2.5 on 2023-09-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmngugiwebsite', '0006_delete_ckeditorimage_alter_blog_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
